workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      variables:
        IMAGE_URL: "https://food-order-prod.s3.eu-west-1.amazonaws.com/15/company/TjH7VHAnE2BdxATWIzmTu2UJTWOP1T9b7iqUCDnT.png"
    scripts:
      - name: Pre-build script to update app icons and launch images
        script: |
          #!/bin/bash
          ./update_icons.sh $IMAGE_URL
    build:
      android:
        flavor: dev
        build_args: --release
      ios:
        export_method: ad-hoc
    artifacts:
      - build/ios/ipa
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      scripts:
        - script: |
            echo "Publishing build artifacts..."
